project_id = "cjodbnsjggslngnzwxsv"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/admin"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_confirmations = true
enable_signup = true

[auth.external.google]
enabled = true
client_id = "1088732041164-ek62j9m3cgangevdshc6h6uu2fg8bg1j.apps.googleusercontent.com"
secret = "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"

[functions.track-click]
verify_jwt = false
